version: 2.1
jobs:

  test:
    docker:
      - image: cimg/node:24.16.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run: npm install npm@11.17.0
      - run: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run prettier
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test